format = """
[╭─](fg:#e4ae81)\
[](fg:#e4ae81)\
[ ](bg:#e4ae81 fg:#090c0c)\
$os\
[](bg:#b86539 fg:#e4ae81)\
$username\
[](fg:#b86539 bg:#8d4018)\
$directory\
[](fg:#8d4018 bg:#642b0e)\
$git_branch\
$git_status\
[](fg:#642b0e bg:#451b06)\
$time\
[ ](fg:#451b06)\
\n[╰──⎸⌾ ](fg:#e4ae81)"""

[os]
disabled = false
format = "[($symbol)($name) ($version) ](bg:#e4ae81 fg:#090c0c)"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[username]
show_always = true
format = '[ ($user) ](fg:#f1d4bc bg:#b86539)'

[directory]
style = "fg:#f1d4bc bg:#8d4018"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#f1d4bc bg:#642b0e)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#f1d4bc bg:#642b0e)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#4d0303"
format = '[[  $time ](fg:#f1d4bc bg:#451b06)]($style)'
